
version: 2

models:
    - name: basic_stats
      description: "Basic stats"
      columns:
          - name: player_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: career_stats_fumbles
      description: ""
      columns:
          - name: player_id
            description: ""
            tests:
                - not_null
    - name: career_stats_passing
      description: ""
      columns:
          - name: player_id
            description: ""
            tests:
                - not_null
    - name: career_stats_receiving
      description: ""
      columns:
          - name: player_id
            description: ""
            tests:
                - not_null
    - name: career_stats_rushing
      description: ""
      columns:
          - name: player_id
            description: ""
            tests:
                - not_null
    - name: game_logs_quarterback
      description: ""
      columns:
          - name: player_id
            description: ""
            tests:
                - not_null
    - name: game_logs_runningback
      description: ""
      columns:
          - name: player_id
            description: ""
            tests:
                - not_null
