sources:
    - name: nfl
      description: NFL Statistics
      database: raw
      schema: nfl
      tables:
          - name: basic_stats
            description: the basic statistics provided for each player.
          - name: career_stats_fumbles
            description: statistics gathered for each player
          - name: career_stats_passing
            description: statistics gathered for each player
          - name: career_stats_receiving
            description: statistics gathered for each player
          - name: career_stats_rushing
            description: statistics gathered for each player
          - name: game_logs_quarterback
            description: game logs for each player.
          - name: game_logs_runningback
            description: game logs for each player.
